Repository cidgoh/DataHarmonizer, pull requests merged in 2020-06, with the labels that each got.

#30 Create LICENSE
  LICENSE
Labels: documentation

#31 Add README.md
  README.md
  images/emptyValidator.png
  images/fieldInfo.png
  images/openingFile.png
  images/validatingGrid.png
Labels: documentation, wip

#32 Stop ignoring blank rows on import
  main.js
Labels: bug

#33 Fix imported integer validation.
  main.js
Labels: bug

#35 Invalidate negative numbers
  main.js
Labels: bug

#36 Fix plain-text import issues
  main.js
Labels: bug

#37 Allow cells with caps settings to be cleared
  main.js
Labels: bug

#38 Show expected and actual secondary headers on import
  main.css
  main.html
  main.js
Labels: enhancement

#43 Fix `mapMatrixToGrid`
  main.js
Labels: bug

#53 GISAID terms and seminal fluid fix
  data.tsv
Labels: bug

#56 Import/export xls files
  main.html
  main.js
Labels: enhancement

#57 Trim trailing blank rows on download
  main.js
Labels: bug

#54 Export to different data formats
  main.html
  main.js
Labels: enhancement

#62 Validate against `dataStatus`
  main.js
Labels: bug, enhancement

#69 Make empty required cells a bit darker
  main.css
  main.js
Labels: enhancement

#72 Browser compatibility in readme
  README.md
Labels: documentation

#73 Link to SOP in "getting started" modal
  SOP.pdf
  main.html
Labels: documentation, enhancement

#75 Update README
  README.md
Labels: documentation

#78 Make GISAID type "betacoronavirus"
  main.js
Labels: bug

#82 Use ``"source"` attr in `data.js` to populate vocabularies
  main.js
Labels: enhancement

#83 Improving many-to-one GISAID mapping
  main.js
Labels: enhancement

#85 Improve performance with large datasets
  libraries/jquery-3.5.1.min.js
  libraries/jquery-3.5.1.slim.min.js
  main.css
  main.html
  main.js
Labels: enhancement

#51 Always read files from the first row
  libraries/xlsx.full.min.js
  main.js
Labels: bug
